function [dff, info] = detrend(rawTraces, opts)
%DETREND Remove double exponential trend
%
% Arguments
%   rawTraces: array, shape (n_time, n_traces)
%       Measurements to detrend along dim 1

arguments (Input)
    rawTraces,
    opts.initialDecay = 0.1,
    opts.maxDecay = 10,
end


N = size(rawTraces, 2);
fit_expr = 'a*exp(-b*x) + c*exp(-d*x)+e';
params = zeros(5, N);
trends = zeros(size(rawTraces, 1), N);
initalDecay = opts.initialDecay;
maxDecay = opts.maxDecay;

parfor i = 1:N

    trace = rawTraces(:, i);

    % Construct parameter ranges from signal range
    signal_floor = min(trace);
    signal_ceil = max(trace);
    fo = fitoptions( ...
        'Method','NonLinearLeastSquares', ...
        'StartPoint',[ ...
            signal_ceil - signal_floor, ...
            initalDecay, ...
            signal_ceil - signal_floor, ...
            initalDecay, ...
            signal_floor], ...
        'Upper',[ ...
            signal_ceil, ...
            maxDecay, ...
            signal_ceil, ...
            maxDecay, ...
            signal_floor], ...
        'Lower',[0 0 0 0 0]);
    ft = fittype(fit_expr,'options',fo);

    % Fit curve and aggregate results
    t_vec = 1:size(trace, 1);
    exp_fit = fit( ...
        t_vec', ...
        trace, ...
        ft);   
    trends(:, i) = exp_fit(t_vec);
    params(:, i) = [
        exp_fit.a, ...
        exp_fit.b, ...
        exp_fit.c, ...
        exp_fit.d, ...
        exp_fit.e];
    
end

dff = rawTraces ./ trends;
info.params = params;
info.trends = trends;

end